name: build

on:
  pull_request:
    types: [locked]
  pull_request_review_comment:
    types: [deleted, created, edited]

jobs:
  set-tags:
    runs-on: [self-hosted, bare-metal]
    steps:
      - run: echo "THIS IS ANOTHER CHANGE"
